sudo: required
services:
  - docker

before_install:
  - docker build -t mexdocker/docker-multi-container -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mexdocker/docker-multi-container npm run test -- --coverage

after_success:
  - docker build -t mexdocker/docker-client ./client
  - docker build -t mexdocker/docker-nginx ./nginx
  - docker build -t mexdocker/docker-server ./server
  - docker build -t mexdocker/docker-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push mexdocker/docker-client
  - docker push mexdocker/docker-nginx
  - docker push mexdocker/docker-server
  - docker push mexdocker/docker-worker
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-multi-container"
  env: "DockerMultiContainer-env"
  bucket_name: "elasticbeanstalk-us-east-2-375469996249"
  bucket_path: "docker-multi-container"
  on:
    branch: master

  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"